### ISSUE TITLE
Support Frida Inject arm64

### ISSUE THREAD

**Issue by apkunpacker** [hluwa/strongR-frida-android#1]
please compile frida inject arm64 also

**Comment by hluwa** [comment]
full binaries release pls see https://github.com/feicong/strong-frida/releases/latest

**Comment by apkunpacker** [comment]
those release become old compare to newest frida  version 15.x , please upload updated build

**Comment by hluwa** [comment]
> those release become old compare to newest frida version 15.x , please upload updated build

Patches are always updated, follow lastest: https://github.com/AAAA-Project/Patchs/tree/master/strongR-frida/frida-core.
15.x automation released see: https://github.com/hluwa/strongR-frida-android/releases/tag/15.0.8.
if actions build failed on lastest frida release, I'll regenerate and upload patches.

**Comment by apkunpacker** [comment]
build success but no frida inject binary there . which is most android user use who not have pc to interact with frida server . although termux now support as host but still most of guy use frida-inject on arm/arm64

**Comment by hluwa** [comment]
> build success but no frida inject binary there . which is most android user use who not have pc to interact with frida server . although termux now support as host but still most of guy use frida-inject on arm/arm64

I see, but sorry i don't plan to upload frida-inject into actions releases for the time being. You can do it self, it's so easy.
